### ISSUE TITLE
Is is possible to create keys that have spaces

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/truebase#28]
true base supports values that contain spaces but is it possible to create keys that contains spaces without confusing the parser ?

**Comment by breck7** [comment]
No. Spaces are not allowed in keys. CamelCase is used instead. If one needs to display a pretty title for an entry one way to work around this is to have a child property such as "label".

There are definitely a lot of languages that support spaces in keys, such as YAML.

My thinking was that it would keep the data easier to work with to have a more restricted character set.

Perhaps I was wrong. Maybe "fuzzy keys", powered by LLMs, might be a better approach. I am not sure.

**Comment by SRS-WRKS** [comment]
Thank you for the clarification. Closing the issue.
